const MODEL='gemini-2.5-flash';
const MAX=100*1024*1024;
const HEAD={'Access-Control-Allow-Methods':'POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-SEO-Prompt,X-SEO-Mime,X-SEO-Filename'};
const res=(d,s=200,o='*')=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json',...HEAD,'Access-Control-Allow-Origin':o}});
const RULES=`You are ZyvenSEO AI, a senior multimodal SEO strategist. Uploaded media is the source of truth. Analyze the actual source, not merely the user label. Never invent facts, people, products, locations, statistics, search volume, rankings, trends, private algorithm signals, quotes, medical/scientific claims or virality guarantees. If evidence is insufficient, say so.
Build exactly 1 primary keyword, 5-8 secondary semantic phrases, 6-10 long-tail queries and 3-5 semantic clusters.
YouTube: 3 distinct titles (search-first, curiosity-first, balanced), concise accurate description, timestamps only when defensible from actual sequence, tags <=400 chars, hook, CTA, thumbnail brief.
Instagram: native micro-blog caption, 3 topic tags, 5-8 relevant hashtags, hook and CTA.
TikTok: search-aware caption, 3 on-screen hooks, 2 broad + 2 niche hashtags, separate trending category; trending status is NOT_CONNECTED unless live data is supplied.
Facebook Reels: conversational headline, readable narrative, discovery keywords, share/save CTA and genuine comment question.
Pinterest: Pin title <100 chars, description <500 chars, keywords, topics, 3 board options, recommended board, save CTA and on-image text.
Each platform must be meaningfully different. Score 0-100 is source-fit editorial quality, not predicted views. Return ONLY JSON.`;
async function parse(r){let t=await r.text(),d;try{d=JSON.parse(t)}catch{d={raw:t}}if(!r.ok)throw Error(d?.error?.message||d?.raw||'AI request failed');return d}
async function exaResearch(env,query){if(!env.EXA_API_KEY)return{status:'NOT_CONNECTED',sources:[]};let r=await fetch('https://api.exa.ai/search',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':env.EXA_API_KEY},body:JSON.stringify({query,numResults:5,type:'auto',contents:{highlights:{maxCharacters:1200}}})});let d=await parse(r);return{status:'CONNECTED',sources:(d.results||[]).map(x=>({title:x.title||'',url:x.url||'',publishedDate:x.publishedDate||'',highlights:x.highlights||[]}))}}\nasync function upload(env,req,mime){let n=Number(req.headers.get('content-length')||0);if(n>MAX)throw Error('File exceeds 100 MB');let s=await fetch('https://generativelanguage.googleapis.com/upload/v1beta/files',{method:'POST',headers:{'x-goog-api-key':env.GEMINI_API_KEY,'X-Goog-Upload-Protocol':'resumable','X-Goog-Upload-Command':'start','X-Goog-Upload-Header-Content-Length':String(n),'X-Goog-Upload-Header-Content-Type':mime,'Content-Type':'application/json'},body:'{"file":{"display_name":"zyvenseo-upload"}}'});if(!s.ok)throw Error('Media upload initialization failed');let u=s.headers.get('x-goog-upload-url');let p=await fetch(u,{method:'POST',headers:{'Content-Length':String(n),'X-Goog-Upload-Offset':'0','X-Goog-Upload-Command':'upload, finalize'},body:req.body});let d=await parse(p),name=d?.file?.name,uri=d?.file?.uri;if(!name||!uri)throw Error('No media URI returned');let state=d?.file?.state;for(let i=0;i<48&&state&&state!=='ACTIVE';i++){await new Promise(r=>setTimeout(r,2500));let q=await fetch('https://generativelanguage.googleapis.com/v1beta/'+name,{headers:{'x-goog-api-key':env.GEMINI_API_KEY}});let z=await parse(q);state=z?.state||z?.file?.state}if(state&&state!=='ACTIVE')throw Error('Media processing timed out');return{uri,mime:d?.file?.mimeType||mime}}
export default{async fetch(req,env){let o=req.headers.get('Origin')||'*';if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{...HEAD,'Access-Control-Allow-Origin':o}});if(req.method!=='POST'||new URL(req.url).pathname!='/analyze')return res({error:'POST /analyze only'},405,o);if(!env.GEMINI_API_KEY)return res({error:'Add GEMINI_API_KEY as a Worker secret.'},500,o);try{let mime=req.headers.get('X-SEO-Mime')||req.headers.get('Content-Type')||'text/plain',prompt=req.headers.get('X-SEO-Prompt')||'';if(!prompt)return res({error:'Missing prompt'},400,o);let research=await exaResearch(env,'SEO research for '+prompt.slice(0,1200));let parts=[{text:RULES+'\nUSER SETTINGS:\n'+prompt+'\nWEB RESEARCH (Exa):\n'+JSON.stringify(research)+'\nUse web research only as supporting evidence. Do not claim search volume, ranking, trend or virality data unless returned sources explicitly provide it.'}];if(req.body){if(mime.startsWith('text/'))parts.push({text:'SOURCE TEXT:\n'+(await req.text()).slice(0,300000)});else{let f=await upload(env,req,mime);parts.push({file_data:{mime_type:f.mime,file_uri:f.uri}})}}let r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+MODEL+':generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':env.GEMINI_API_KEY},body:JSON.stringify({contents:[{role:'user',parts}],generationConfig:{responseMimeType:'application/json',temperature:.28,maxOutputTokens:8192}})});let d=await parse(r),text=d?.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('');return res({text},200,o)}catch(e){return res({error:e?.message||'Analysis failed'},500,o)}}};